Now included:
(1) combined checking misuse of Author_evidence and convert Author to Person:

    Sample output:

       RROR: Locus abt-1 has non-Person Sheps JA under main tag Evidence
       UPDT: Locus abt-1 has Author Sheps JA under main tag Evidence
       =====>Author Sheps JA can now be Person WBPerson583

       ERROR: Locus gna-2 has Author Dennis, JW under main tag Genomic_sequence
       UPDT: Locus gna-2 has Author Dennis, JW under main tag Genomic_sequence
       =====>Author Dennis, JW can now be Person WBPerson1822


(2) showing which Authors are not yet Persons (by -i OR -info option)

    Sample output:

       INFO: Locus csn-5 has Author Pintard L under main tag Genomic_sequence: NOT a Person object

(3) statistics

    Sample output:

	   There are 54 Evidence errors in 7 classes checked

	   893 Authors can be converted to Persons

	   91 Authors are not Persons


The next step: add codes for acefile output