Added "Checking discrepancies in genetics/coords mapping"
This is called from geneace_ckeck.pl to system execute cmp_gmap_physical_location.pl using -diff option

Sample output:


Checking discrepancies in genetics/coords mapping:

C54A12.1 (daf-6) is mapped to X by genetics
C54A12.1 (daf-6) is mapped to II by coordinates.

Y51A2D.19a (sle-1) is mapped to II by genetics
Y51A2D.19a (sle-1) is mapped to V by coordinates.

Y51A2D.19b (sle-1) is mapped to II by genetics
Y51A2D.19b (sle-1) is mapped to V by coordinates.

Y51A2D.19c (sle-1) is mapped to II by genetics
Y51A2D.19c (sle-1) is mapped to V by coordinates.

ZC395.7 (ham-1) is mapped to IV by genetics
ZC395.7 (ham-1) is mapped to III by coordinates.

ERROR: There are 5 discrepancies in genetics/chrom. coords mapping